version: "3.8"

services:
  app:
    build: .
    ports:
      - "3300:3300"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/employee_management_api
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
